# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAccion', models.CharField(max_length=150)),
                ('InfoControl', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAccion', models.DateField(default=django.utils.timezone.now)),
                ('Afectado', models.CharField(max_length=50, null=True)),
                ('Accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Accion')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuenasPracticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Carie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombres del paciente')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellidos del paciente')),
                ('dui', models.CharField(blank=True, help_text='Formato: XXXXXXXX-X', max_length=10, null=True, unique=True, verbose_name='Número de DUI')),
                ('nit', models.CharField(blank=True, help_text='Formato: XXXX-XXXXXX-XXX-X', max_length=17, null=True, unique=True, verbose_name='Número de NIT')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(help_text='Formato: XXXX-XXXX', max_length=9, verbose_name='Número de teléfono')),
                ('direccion', models.CharField(help_text='Dirección de su residencia', max_length=80, verbose_name='Dirección')),
                ('estado_civil', models.CharField(choices=[('C', 'Casado'), ('S', 'Soltero'), ('V', 'Viudo'), ('D', 'Divorciado')], max_length=1, verbose_name='Estado Civil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Empleado',
                'ordering': ['expediente'],
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_expediente', models.CharField(max_length=5, unique=True, verbose_name='Número de expediente')),
                ('fecha_apertura', models.DateField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('empleado', models.OneToOneField(help_text='Expediente asignado', on_delete=django.db.models.deletion.CASCADE, to='api.Empleado')),
            ],
            options={
                'verbose_name': 'Expediente',
                'ordering': ['num_expediente'],
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='HistorialOdonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EvalSistem', models.CharField(max_length=50)),
                ('FrecCepilla', models.IntegerField()),
                ('HabitosBucal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de realizacion')),
                ('plan', models.CharField(max_length=512, verbose_name='Acciones correctivas')),
                ('control', models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Fecha de proximo control')),
                ('buenas_practicas', models.ManyToManyField(blank=True, to='api.BuenasPracticas')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edad', models.IntegerField()),
                ('Sexo', models.CharField(max_length=1)),
                ('Residencia', models.CharField(max_length=1)),
                ('FechaConsul', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posicion', models.IntegerField()),
                ('EstOMS', models.CharField(max_length=50)),
                ('EstICDAS', models.CharField(max_length=50)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Superficie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posicion', models.IntegerField()),
                ('CodSuper', models.IntegerField()),
                ('NomSuper', models.CharField(max_length=255)),
                ('EstICDAS', models.CharField(max_length=50)),
                ('EstOMS', models.CharField(max_length=50)),
                ('CodCar', models.IntegerField()),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTratam', models.CharField(max_length=255)),
                ('CodDental', models.IntegerField()),
                ('Caries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Carie')),
            ],
        ),
        migrations.AddField(
            model_name='superficie',
            name='Tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tratamiento'),
        ),
        migrations.AddField(
            model_name='historialodonto',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paciente'),
        ),
    ]
