# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialodonto',
            name='Paciente',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='Paciente',
        ),
        migrations.RemoveField(
            model_name='superficie',
            name='Paciente',
        ),
        migrations.RemoveField(
            model_name='superficie',
            name='Tratamiento',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='Caries',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellidos del empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombres del empleado'),
        ),
        migrations.DeleteModel(
            name='Carie',
        ),
        migrations.DeleteModel(
            name='HistorialOdonto',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Pieza',
        ),
        migrations.DeleteModel(
            name='Superficie',
        ),
        migrations.DeleteModel(
            name='Tratamiento',
        ),
    ]
