# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181120_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accion',
            name='InfoControl',
        ),
    ]
